apiVersion: v1
kind: Pod
metadata:
  name: storagetestpod
spec:
  containers: 
  - name: gpu-container
    image: gitlab-registry.nautilus.optiputer.net/prp/jupyterlab:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
  - name: vol-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: https://raw.githubusercontent.com/byungheon-jeong/tensorflowNode-mk1/master/blockstorageconfig.yaml
      name: examplevol
  restartPolicy: Never
  volumes:
    - name: examplevol
      persistentVolumeClaim:
        claimName: examplevol
